package tester.test;

import static java.util.Arrays.asList;

import java.lang.String;
import java.util.List;

/**
 * This class is autogenerated using ResourceIndexer.
 * Dont modify it manually cause it will we overwritten next time its generated.
 */
public final class R {
  public static final String bojan = "bojan.txt";

  public static final class images {
    public static final String regenbar = "images/regenbar.jpg";

    public static List<String> getFiles() {
      return asList(regenbar);
    }

    public static String getPath() {
      return "src/main/resources/images";
    }
  }

  public static final class test {
    public static String getPath() {
      return "src/main/resources/test";
    }
  }

  public static final class tester {
    public static final String R = "tester/R.java";

    public static List<String> getFiles() {
      return asList(R);
    }

    public static String getPath() {
      return "src/main/resources/tester";
    }
  }

  public static final class text {
    public static final String _0_t_text_A = "text/0+t text-A.txt";

    public static final String bojan = "text/bojan.txt";

    public static List<String> getFiles() {
      return asList(_0_t_text_A,bojan);
    }

    public static String getPath() {
      return "src/main/resources/text";
    }

    public static final class text1 {
      public static final String textB = "text/text1/textB.txt";

      public static List<String> getFiles() {
        return asList(textB);
      }

      public static String getPath() {
        return "src/main/resources/text/text1";
      }

      public static final class text3 {
        public static final String textC = "text/text1/text3/textC.txt";

        public static List<String> getFiles() {
          return asList(textC);
        }

        public static String getPath() {
          return "src/main/resources/text/text1/text3";
        }
      }
    }

    public static final class text2 {
      public static final String textD = "text/text2/textD.txt";

      public static List<String> getFiles() {
        return asList(textD);
      }

      public static String getPath() {
        return "src/main/resources/text/text2";
      }
    }
  }
}
