package tester;

import java.lang.String;

/**
 * This class is autogenerated using ResourceIndexer.
 * Dont modify it manually cause it wil
 * we overwritten next time its generated.
 */
final class R {
  public static final class images {
    public static final String regenbar = "src\\main\\resources\\images\\regenbar.jpg";

    public static String getPath() {
      return "src/main/resources/images";
    }
  }

  public static final class test {
    public static String getPath() {
      return "src/main/resources/test";
    }
  }

  public static final class tester {
    public static final String R = "src\\main\\resources\\tester\\R.java";

    public static String getPath() {
      return "src/main/resources/tester";
    }
  }

  public static final class text {
    public static final String _0_t_text_A = "src\\main\\resources\\text\\0+t text-A.txt";

    public static String getPath() {
      return "src/main/resources/text";
    }

    public static final class text1 {
      public static final String textB = "src\\main\\resources\\text\\text1\\textB.txt";

      public static String getPath() {
        return "src/main/resources/text/text1";
      }

      public static final class text3 {
        public static final String textC = "src\\main\\resources\\text\\text1\\text3\\textC.txt";

        public static String getPath() {
          return "src/main/resources/text/text1/text3";
        }
      }
    }

    public static final class text2 {
      public static final String textD = "src\\main\\resources\\text\\text2\\textD.txt";

      public static String getPath() {
        return "src/main/resources/text/text2";
      }
    }
  }
}
